export const DASHBOARD_ROUTES = [
  'login',
  'dashboard',
  'onboarding',
  'my-profile',
  'edit-profile',
  'bonus',
  'giveaways',
  'tradejournal',
  'review-panel',
  'challenges-panel',
  'announcements-panel',
  'rules-panel',
  'dashboard-admin',
  'support-dashboard',
  'admin-activity',
  'admin-announcements',
  'admin-beginner-tutorials',
  'admin-clients',
  'admin-community',
  'admin-content-cms',
  'admin-events',
  'admin-faqs',
  'admin-filters',
  'admin-firm-details',
  'admin-firms',
  'admin-funding-strategies',
  'admin-giveaways',
  'admin-moderation',
  'admin-newsletter',
  'admin-offers',
  'admin-propnews',
  'admin-purchases',
  'admin-reviews',
  'admin-support-access',
  'admin-trading-guides',
  'admin-trading-psychology',
] as const

export const PUBLIC_STATIC_ROUTES = [
  'prop-news',
  'prop-news-post',
  'content-post',
  'trading-guides',
  'funding-strategies',
  'trading-psychology',
  'beginner-tutorials',
  'giveaway',
  'reviews',
  'firm-reviews',
  'broker-coming-soon',
  'offers',
  'discount-offer',
  'prop-firm-rules',
  'firm-rules',
  'compare',
  'listedprop',
  'bestprop',
  'beginner-friendly-firms',
  'highest-rated-firms',
  'best-instant-funding-firms',
  'best-futures-prop-firms',
  'best-hft-prop-firms',
  'best-prop-firms-2026',
  'cheapest-prop-firms',
  'fast-payout-prop-firms',
  'most-trusted-prop-firms',
  'aquafundeddetail',
  'blueberrydetail',
  'blueberryfundeddetail',
  'blueguardiandetail',
  'directfundingtraderdetail',
  'finotivefundingdetail',
  'firm-detail',
  'fundednextdetail',
  'funderprodetail',
  'fx2fundingdetail',
  'fxifydetail',
  'goatfundedtraderdetail',
  'instantfundingdetail',
  'qtfundeddetail',
  'swayfundeddetail',
  'theproptradedetail',
  'toponetraderdetail',
  'traderscaledetail',
  'wefunddetail',
  'calculators',
  'lotsizecalculator',
  'risk-to-reward-calculator',
  'drawdown-calculator',
  'profit-split-calculator',
  'consistency-rule-calculator',
  'lossrecoveryplanner',
  'ruletranslator',
  'about',
  'contact',
  'legal',
  'disclaimer',
  'privacy-policy',
  'terms',
  'cookies-policy',
] as const

export const PUBLIC_ROUTE_REDIRECTS: Record<string, string> = {
  '/discount': '/offers',
  '/privacypolicy': '/privacy-policy',
  '/termsofservice': '/terms',
  '/cookiespolicy': '/cookies-policy',
  '/cookie-policy': '/cookies-policy',
}
